name: Compilação Manual do APK (Final)
on:
  push:
    branches:
      - principal
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Passo 1: Instala o libtinfo5 manualmente
      - name: Instalar libtinfo5 manualmente
        run: |
          # Baixa o pacote de um mirror conhecido e estável do Ubuntu
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.2-1ubuntu1_amd64.deb
          # Instala o pacote .deb baixado
          sudo dpkg -i libtinfo5_6.2-1ubuntu1_amd64.deb

      # Passo 2: Instala o restante das dependências do sistema
      - name: Instalar outras dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            libffi-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libssl-dev \
            pkg-config \
            python3-setuptools \
            zlib1g-dev

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Buildozer e Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Compilar APK com Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Carregar APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_APK
          path: bin/*.apk
