# Commit para forçar a compilação do Actions 
name: Compilação Android Kivy/Buildozer

on:
  push:
    branches:
      - principal # Correção do branch
  workflow_dispatch: # Adicione esta linha para criar o botão 'Run workflow'
jobs:
  build:
    runs-on: ubuntu-latest # Deve ser 'runs-on', não 'continua'

    steps:
      - name: Checkout Código Fonte
        uses: actions/checkout@v4

      - name: Compilar APK com Buildozer
        uses: kivy-actions/buildozer-action@v1 # <- NOVA AÇÃO ESTÁVEL
        id: buildozer
        with:
          buildozer_args: android debug

      - name: Upload APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_APK
          path: bin/*.apk
          retention-days: 7
