name: Compilação Android via Briefcase
on:
  push:
    branches:
      - principal
  pull_request:
    branches:
      - principal
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código Fonte
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build Android APK
        # A linha abaixo DEVE incluir @v1 para ser encontrada pelo GitHub
        uses: beeware/briefcase-action@v1
        with:
          command: build
          platform: android
          # O Briefcase lerá o buildozer.spec para os requisitos (kivy==2.2.1)

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_APK
          # O Briefcase gera o APK em um caminho diferente do Buildozer puro
          path: '*/android/gradle/app/build/outputs/apk/debug/*.apk'
