name: Depoy manual #Compilação Android Kivy/Buildozer

on:
  push:
    branches:
      - principal # Este é o seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest # Usa o Ubuntu mais recente para a compilação

    steps:
      - name: Checkout Código Fonte
        uses: actions/checkout@v4

      - name: Compilar APK com Buildozer
        uses: ulyng/buildozer-action@v1.1
        id: buildozer
        with:
          buildozer_version: '1.4.0' # Versão estável
          command: buildozer android debug

      - name: Upload APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_APK
          path: bin/*.apk
          retention-days: 7
